# Generated by Django 3.1.5 on 2021-01-12 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='barcode',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
