# Generated by Django 3.1.5 on 2021-01-09 11:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='pub_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
